### ISSUE TITLE
Simple home page

### ISSUE THREAD

**Issue by yyx990803** [vuejs/theme#17]
Similar to the current VitePress [Home component](https://github.com/vuejs/vitepress/blob/master/src/client/theme-default/components/Home.vue) but with new styling.

This can be used by projects like `vue-router` etc.

**Comment by Jinjiang** [comment]
Confirmed with @yyx990803 offline: this `theme` repo will only be used to serve the Vue official website, which is now fulfilled already. The rest planned issues like this would be considered moving to the default theme of vitepress. So close this one. Thanks.
