### ISSUE TITLE
Use shiki's latest API for code block with line highlights

### ISSUE THREAD

**Issue by octref** [vuejs/theme#41]
Was poking around the new site to see Shiki's usage in the wild. I think the current line highlighting solution can be simplified.

Shiki 0.10.0 adds an API to highlight specific lines. For example, this:

```js
highlighter
  .codeToHtml(code, {
    lang,
    theme,
    lineOptions: [
      { line: 2, classes: ['highlighted']}
    ]
  })
```

generates something like:

```html
<span class="line"></span>
<span class="line highlighted"></span>
<span class="line"></span>
```

The current line highlighter uses a workaround by rendering two layers, one with the highlighted code and the other one with all `<br>`. By using the API it cuts some HTML for code blocks with highlighted lines:

![image](https://user-images.githubusercontent.com/4033249/147598397-705f9156-9d86-4d8e-80ff-6ba2161eba53.png)

I have a PR - should I wait until this repo is more stabalized to send it?

**Comment by yyx990803** [comment]
Sorry for letting this sit - the theme is stable now and a PR is most welcome!

**Comment by Jinjiang** [comment]
It seems should be done on the vitepress repo instead: https://github.com/vuejs/vitepress

more precisely, replacing this plugin:
https://github.com/vuejs/vitepress/blob/70b3060be963ed7a0d2041446d67ac970d6f35e3/src/node/markdown/plugins/highlightLines.ts

**Comment by octref** [comment]
@Jinjiang Thanks!
