### ISSUE TITLE
Will @vue/theme be the theme for vitepress?

### ISSUE THREAD

**Issue by Hongbusi** [vuejs/theme#43]
Hello~

The new vue3 documentation will be the best development documentation.
Thanks to the vue team for bringing us such a good documentation experience.

Also want to know, @vue/theme will optimize the hardcoded logic specific to Vue documentation to become the official vitepress theme?

Thanks!

**Comment by Hongbusi** [comment]
For example: https://github.com/vuejs/theme/blob/main/src/vitepress/components/VPNavBarTitle.vue

**Comment by antfu** [comment]
In the README:
> Please note this theme is solely dedicated for vuejs.org and isn't meant to be used as a content-neutral theme. It does not follow semver and may contain hard-coded logic specific to the Vue documentation.

@kiaking is designing a new theme for VitePress tho 👀

**Comment by Hongbusi** [comment]
> 



> In the README:
> 
> > Please note this theme is solely dedicated for vuejs.org and isn't meant to be used as a content-neutral theme. It does not follow semver and may contain hard-coded logic specific to the Vue documentation.
> 
> @kiaking is designing a new theme for VitePress tho 👀

Thank you for your answer.

**Comment by Hongbusi** [comment]
@antfu Thank you very much.
