### ISSUE TITLE
Code Group Component

### ISSUE THREAD

**Issue by JessicaSachs** [vuejs/theme#46]
I need a VTCodeGroup for the docs -- I rolled my own, but it's coupled to what I'm putting inside of it. We should have one that matches the theme and is generic.

https://github.com/vuejs/docs/pull/1493#issuecomment-1037925511

**Comment by JessicaSachs** [comment]
If I wanted to pick this up is there any issue with the UI I chose in the PR above? @kiaking maybe? (or Evan, idk who to summon)

**Comment by kiaking** [comment]
@JessicaSachs I think the UI is matching the taste of the whole theme 👍  Great job! If I may comment, maybe we could:

1. Make `tab` font size to 14px? Feels just a little bit big. I don't know 🤔 
2. Add `text-overflow: ellipsis;`, for Mobile design (more about this in below)

Currently the tag names get wrapped at mobile view.

<img width="379" alt="Screen Shot 2022-02-17 at 9 45 33" src="https://user-images.githubusercontent.com/3753672/154382492-c1b68993-4b57-4922-be5f-f2bd31ad08c3.png">

If not doing `text-overflow: ellipsis;`, then maybe making the font-size and line-height smaller and make it vertically centered might be nice too...?

**Comment by JessicaSachs** [comment]
Yeah I can make it pretty for mobile. I knew it wasn't scaling for
different length text, but I figured we'd make it more resilient once we
added to the theme/component library.
