### ISSUE TITLE
layout slots Not enough

### ISSUE THREAD

**Issue by wanlum** [vuejs/theme#48]
(https://github.com/vuejs/theme/tree/main/src/vitepress/components)/VPNavBarTitle.vue

In this file, there are many places that are hard-coded, such as logo images and vue.js, can we leave the slot and let us define it ourselves

<img width="898" alt="image" src="https://user-images.githubusercontent.com/11306760/154600709-63802ef1-b42e-42fb-9e8c-83f9ec079749.png">

thank you!

**Comment by Jinjiang** [comment]
@wanlum thank you for your advice. After consideration, we decided to let this job be handled by [the default theme of vitepress](https://github.com/vuejs/vitepress/blob/main/src/client/theme-default/components/VPNavBarTitle.vue). This repo in the future will only serve the Vue official website. So I guess it's still cool to hardcode it. Hope you won't mind. 🙏
