### ISSUE TITLE
If the search is not set, an error will appear

### ISSUE THREAD

**Issue by shibin-cli** [vuejs/theme#53]
![image](https://user-images.githubusercontent.com/72774429/158922734-52dbc007-58b4-411c-9ecd-0a2e68e48c8a.png)
If algolia is not set，the following error message will appear
![image](https://user-images.githubusercontent.com/72774429/158918808-df1c58a0-f8e4-46ea-b8aa-9baafb753186.png)

![image](https://user-images.githubusercontent.com/72774429/158919759-f2a03d80-5e58-4d7d-af51-c67d51c73bc8.png)

![image](https://user-images.githubusercontent.com/72774429/158921028-1b21804a-c5d8-4728-a847-b45377ef0407.png)

**Comment by Jinjiang** [comment]
Fixed by #47
