### ISSUE TITLE
Code block style problem

### ISSUE THREAD

**Issue by flingyp** [vuejs/theme#54]
In the demo module, it is found that when the automatic line number configured for vitepress is true, the following problems will occur when using the custom code block vue-html, class line-numbers-mode is missing. There is also a problem with the font color of bright mode line size text.
![{D{}X0UUVU)Q0QOJ76KS~HY](https://user-images.githubusercontent.com/57666140/159887538-f8fa0da6-72da-4724-b098-21874943ee3d.png)

**Comment by Jinjiang** [comment]
@flingyp after double-checking, the official Vue doc site currently doesn't enable the line number mode. So it won't affect anything here. I think it's a bug of Vitepress, so I created another one there to keep on track further. Thanks.

https://github.com/vuejs/vitepress/issues/1105
