### ISSUE TITLE
Use Chinese Title Questions

### ISSUE THREAD

**Issue by liuxm721** [vuejs/theme#62]
![image](https://user-images.githubusercontent.com/64787292/170609914-5653d9a6-9cfd-4864-a590-6dc4941b5509.png)

**Comment by liuxm721** [comment]
Thank you, but it's not about the file name. It's about the  side navigation. 
![动画](https://user-images.githubusercontent.com/64787292/170611515-58116258-f43f-48f2-a16a-2e4fa6d9820f.gif)

**Comment by Jinjiang** [comment]
@liuxm721 may I know whether the bug is still there or fixed? Thanks.

**Comment by Jinjiang** [comment]
Since it's not about the theme but more about VitePress, I'd like to close this issue. Further discussion could happen on either VitePress or docs repo. Thanks.
