### ISSUE TITLE
href on div element

### ISSUE THREAD

**Issue by xfq** [vuejs/theme#85]
https://github.com/vuejs/theme/blob/c48d95cac36bb46196d38fe5e028da9b39d5d367/src/vitepress/components/VPNavBarLocaleItems.vue#L22-L26

The `div` element has an `href` attribute here, but [according to the HTML Standard](https://html.spec.whatwg.org/multipage/grouping-content.html#the-div-element), only [global attributes](https://html.spec.whatwg.org/multipage/dom.html#global-attributes) are allowed. It would be great if it can be changed to something like [data-href](https://html.spec.whatwg.org/multipage/dom.html#embedding-custom-non-visible-data-with-the-data-*-attributes).

**Comment by Jinjiang** [comment]
@xfq thanks so much for pointing this out. I've refactored the implementation. Feel free to take a look. 🙏
