### ISSUE TITLE
能将 vuejs.org 官网的ui封装成一个Vue的UI框架吗？

### ISSUE THREAD

**Issue by SoXunwa** [vuejs/theme#87]
真的喜欢 https://vuejs.org 官网的UI样式，
比传统的 Vue UI框架好看，
能将它封装成一个像 element-ui (https://element-plus.org/) 一样的 Vue UI框架吗？
目前流行的  Vue UI 框架的样式设计像是停留在十年前，真的太丑太LOW了，根本不符合现在年轻人的审美。

**Comment by Jinjiang** [comment]
https://github.com/vuejs/ui
可以关注一下这个组件库，更多想法可以在那里讨论
谢谢
