### ISSUE TITLE
Incorrect aside sticky position

### ISSUE THREAD

**Issue by Hfutsora** [vuejs/theme#90]
When there is a top banner and no sidebar, the sticky position of the aside is incorrect.

![image](https://user-images.githubusercontent.com/31959015/226567787-1c1321e3-adea-4082-ac5c-5c8a9e4eb11c.png)

You can find this bug on [vue doc](https://vuejs.org/about/faq.html).

Related: [vitepress issue](https://github.com/vuejs/vitepress/issues/2114).

**Comment by Hfutsora** [comment]
![3 USS8D2_~ }YORU54_U@OH](https://user-images.githubusercontent.com/31959015/226782931-cbfcf7ec-98b6-4551-97b7-ddc70d6bfdee.png)

The problem seems to be caused by the top advertising banner not providing `vt-banner-height`. 

![image](https://user-images.githubusercontent.com/31959015/226783389-4f5cf5c6-1605-4c21-b6bf-c76020149813.png)

Manually adding the `vt-banner-height` seems to have fixed the issue.

**Comment by Jinjiang** [comment]
So I guess this issue can be closed. Thanks all.
