### ISSUE TITLE
Missing `active` class on active sidebar item for examples page

### ISSUE THREAD

**Issue by palamarchukser** [vuejs/theme#97]
no `active` styles after load/reload page
https://vuejs.org/examples/#handling-input

![image](https://github.com/vuejs/docs/assets/10272176/1a6179ba-46bd-4447-87ff-3be914272592)

**Comment by Jinjiang** [comment]
@brc-dd do you think we can or already support that (sidenav highlight on URL hash changes) in VitePress?

**Comment by brc-dd** [comment]
This line should've handle that:

https://github.com/vuejs/theme/blob/f12c2e957c6fb78013061ea6f7379f68915b9ad6/src/vitepress/components/VPSidebarLink.vue#L17

I'll take a look why it isn't working on initial load.

**Comment by brc-dd** [comment]
Hi, can't seem to make it work yet. Encountered the same thing at VitePress' default theme too: https://github.com/vuejs/vitepress/pull/2736/files#diff-a0153043e1db682101638d1ba11fbc5248fad17edaa05ed671b22d057d8db2cb

We can do something like this to workaround the issue:

```ts
const active = ref(false)

const checkActive = () => {
  return isActive(page.value.relativePath, item.value.link)
}

onMounted(() => {
  active.value =  checkActive()
})

// ...

:class="{ link: true, active: active || checkActive() }" 
```
